### ISSUE TITLE
Bug with 14-5-19 on untimed test 4

### ISSUE THREAD

**Issue by pamelafox** [RunestoneInteractive/rs#179]
This code is claimed to be correct, but it has 2 bugs: 1) it is an infinite loop, since num is never equal to 0, and 2) it has an extra semi-colon after i--

// I.
for (int i = num; num > 0; i--;)
{
    System.out.print (i + " ");
}

**Comment by barbarer** [comment]
Any idea which book this was and where?

**Comment by pamelafox** [comment]
I filed it back when I was helping out a CS A classroom, so we were using the textbook that used to be here:

https://runestone.academy/runestone/static/JavaReview/Tests/test4nt.html
