### ISSUE TITLE
Exclude problems in an exercises section from the reading assignment cout

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#257]

**Comment by rbeezer** [comment]
I know exactly when these problems hit the manifest.  Did we decide how to flag them?  We can talk Tuesday.

**Comment by bnmnetp** [comment]
The flag in the database is called `optional`  So if we can just add that to the manifest for a question that will work great.

**Comment by rbeezer** [comment]
`optional="yes"` is now on `<question>` for manifest enties coming out of an `<exercises>` division.

At https://github.com/PreTeXtBook/pretext/commit/2750a583905c4bfb910fdad523b3ace9196b24ad

**Comment by rbeezer** [comment]
Can't close this, nor could I figure out how to add #283 into the project.  :-(

**Comment by bnmnetp** [comment]
I've been trying to check this with the latest nightly prerelease.  1.6.1.dev20230704

I do not see any `optional="yes"` in the the active calculus book manifest.  Specifically the safranski-acs book that Chrissy used.   For example section 7.4 has an exercises division but I'm not seeing any optional in the manifest.    

Do I need any other flags to enable?

**Comment by rbeezer** [comment]
Let's back up a step.

* Can you see if you have `2750a583905c4bfb910fdad523b3ace9196b24ad` from June 27?
* Build the sample book?  I just did (cuz it was convenient) and got loads of `@optional`.

If that checks out, then we can see what sorts of things AC is up to.

**Comment by bnmnetp** [comment]
when I run pretext show it says I have:

```
PreTeXt-CLI version: 1.6.1.dev20230704
    PyPI link: https://pypi.org/project/pretextbook/1.6.1.dev20230704/
PreTeXt core resources commit: d0c0cf9e039e95a0d1cf57dbf1a5a00c2a5e866e
Runestone Services version: 6.5.0
OS: macOS-13.5-arm64-arm-64bit
Python version: 3.10.9
Current working directory: /Users/bmiller/.ptx/xsl
No project.ptx found.
```

Since that commit is from July 3rd I should have the the one from June 27

**Comment by bnmnetp** [comment]
Can hop on zoom if you want to debug real time.

**Comment by rbeezer** [comment]
Sure - send me a link?

**Comment by bnmnetp** [comment]
Its the same one as for all the dropins - https://prose.runestone.academy/dropin/

**Comment by rbeezer** [comment]
OK, WeBWorK `exercise` were not being picked up, and those were the **only** interactive exercises in ACS/Safranski, hence it seemed this had  no effect.  Fixed, and then a refactor so that maybe this sort of thing won't get missed again.

Addressed at: https://github.com/PreTeXtBook/pretext/commit/bdace5de05598cea6888a98b088457c68e63c159
Refactored at: https://github.com/PreTeXtBook/pretext/commit/a6a25b78566917b63f84f1e6974d71105e7d5934
