### ISSUE TITLE
:datafile: for file input and :stdin: not working for Java/Jobe

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/rs#282]
I have not been able to get :stdin: and  :datafile: to work in Java on the JOBE server on Runestone. The Java :stdin: example here https://runestone.academy/ns/books/published/authorguide/directives/activecode.html?mode=browsing gives a server error.  The datafile that I tried is here: https://runestone.academy/ns/books/published/csawesome/Unit6-Arrays/topic-6-2-traversing-arrays.html?mode=browsing#groupwork-programming-challenge-spellchecker. It gives a server error too. Maybe it's too big of a file though.
I do use :datafile: with images in the picture lab and they work fine there.

**Comment by bnmnetp** [comment]
@bhoffman0 Did the CSAwesome example work at some point?  Or was this something new?

**Comment by bhoffman0** [comment]
Ah, requested entity too large. I'll try a smaller file.
<img width="179" alt="image" src="https://github.com/RunestoneInteractive/rs/assets/4571962/c7d50c5c-dc49-487d-9d67-c1a38474027e">

**Comment by bnmnetp** [comment]
Wow that example is really out of date.  We have not used the jobe server in NZ for many years.

**Comment by bnmnetp** [comment]
This page:  https://runestone.academy/ns/books/published/overview/ActiveCode/java.html I'm not sure but I think the temp conversion example must use stdin

**Comment by bhoffman0** [comment]
Thanks! I'll compare the code for stdin and try a smaller file for datafile.

**Comment by bhoffman0** [comment]
This turned out to be a bug in CodeTestHelper.java used on JOBE which was causing an exception on main methods with throws IOException for File I/O. Peter Seibel fixed the bug here https://github.com/bhoffman0/CSAwesome/blob/master/CodeTestHelper.java

**Comment by bnmnetp** [comment]
OK, but the official version of the CodeTestHelper.java file is in the ~/rs repository so that if there are updates and fixes it will get built automatically when we rebuild all of our containers.  Tagging @gigamonkey

**Comment by bhoffman0** [comment]
Should I do a PR? Do you need the .class file that's in there?

**Comment by bnmnetp** [comment]
No class file is needed as it is just going to get recompiled by jobe when it notices that the .java file is newer.

**Comment by gigamonkey** [comment]
@bnmnetp Are you sure about that. It looks like the current `CodeTestHelper.class` is checked into git. And I don't know of anything in Jobe that even knows about the files the the rs Dockerfile copies into /usr/local/lib/java let alone automatically compiling them.

**Comment by bnmnetp** [comment]
Well, I just rebuilt the jobe image without copying any .class files and sure enough it made them. 

I was quite certain that would be the case, as in the past it has tried to compile a new .java file and we have run into permissions problems with it not being able to overwrite the existing .class file.

**Comment by bnmnetp** [comment]
And remember that /usr/local/lib/java and some of the .jar files are added to the classpath by runguard.

**Comment by gigamonkey** [comment]
TIL that if you compile Foo.java and it depends on the class Bar and Bar.java exists somewhere on the classpath, it will compile it. (I knew it would find referenced Java files but usually I thought of those being in the `--sourcepath` not the `--classpath`. But apparently if sourcepath is not set it uses classpath for that too.)
