### ISSUE TITLE
Groupwork

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#285]

**Comment by bnmnetp** [comment]
Proposal:

Make an exercises division with an @groupwork attribute

If the groupwork attribute is present then we will add the code for picking group members and submitting on behalf of the group.

This will limit the scope of the groupwork to the exercises division rather than the full page.  but I think is a better solution overall.

**Comment by barbarer** [comment]
Can we have another one that refers to the whole page?  I need that for Pogil activitiesSent from my iPhoneOn Jun 27, 2023, at 11:53 PM, Bradley Miller ***@***.***> wrote:﻿
Proposal:
Make an exercises division with an @groupwork attribute
If the groupwork attribute is present then we will add the code for picking group members and submitting on behalf of the group.
This will limit the scope of the groupwork to the exercises division rather than the full page.  but I think is a better solution overall.

**Comment by rbeezer** [comment]
PreText source has no notion of what becomes a page.  Or rather, a publisher has many options for how granular a page is.

But in the Runestone model if a PreText "exercises" division is a child of a "chapter" then it will be a whole page.

**Comment by bnmnetp** [comment]
@rbeezer - Here is an example of a page in barbs book that has group work.
https://runestone.academy/ns/books/published/py4e-int/files/csv-file-group.html?mode=browsing

@barbarer  I think our solution will work for what you are doing. an `exercises` is a grouping of a bunch of individual `exercise`

**Comment by bnmnetp** [comment]
Brad needs to update his code to iterate over all `assignment_partner_select` things and populate the select. 

will need to do the same for `groupsub_button`

**Comment by barbarer** [comment]
Okay, then that is fine.

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by rbeezer** [comment]
Changes pushed, primarily at:

https://github.com/PreTeXtBook/pretext/commit/b92f4bce193884c6055fbc045f30b2428c5fcdc6

Makes all `exercise` inside an `exercises` into a group work activity, but only if the `exercises` is at the `subchapter` level.  This condition could be relaxed, see below.   Only if hosted at RA.  Collection of multiple choice questions in sample book has been enabled as group work.

Notes:
* Two `id` have become `class`.
* Retained `style="width:100%` on `select`, but could now be part of CSS based on the class?
* No overall  `ptx-runestone-container`.

Now, more generally.
*  Progress indicator sits at the bottom of any page at the "subchapter" level.  (But not `exercises` that have extra features.)
*  Timed exams have `exercise` that are **wrapped** inside of the Runestone component.
*  Group work `exercise` **are not wrapped** inside a component.

Question: if group work behaved like timed exams, we could broaden the possibilities to one or more of 
a.  `exercises` not at "subchapter" level
b.  `exercisegroup`
c.  subexercises`

No problem saving the dfiscussion for a Drop-In.
