### ISSUE TITLE
Integrate the landing page into the default controller

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#292]

**Comment by bnmnetp** [comment]
Currently `default/index` has a requires_login on it, which immediately redirects new non-registered users to login.

I would like to change this to redirect non-logged in users to https://landing.runestone.academy

If a user **is** logged in they will be redirected to their course or the choose a course page.

From the landing page the user could select the login button / or the register button.

@bhoffman0 - Do you think this would be too much of a shock?  the main difference would obviously be the look and then the need to click on a button if they needed to login.

This would not change anything for people coming in from LTI.

**Comment by bhoffman0** [comment]
A landing page is a good idea, but this does look very different than the current Runestone page which could be confusing. I thought I had gone to a different site. I would try to keep the look similar and simpler with as few pages as possible (sections in one page would be better), and make sure they know they are on the Runestone site, and it's clear where to go to Login (I clicked on Get Started first which led me somewhere else)  I'm not sure about using stock photos. Also, the navbar has some links on top of each other.

**Comment by bnmnetp** [comment]
Yes, I know it is different.  But the whole board of directors said we needed to get a better front page so that people who don't know who we are have a place to land that looks like a real, professional, place.

This is an early prototype and we are working on getting a prominent login button that takes people back to the familiar Runestone site.  But, once students are logged in they won't see this.  Plus the logo is quite prominent so they should understand it is the same place Runestone Academy.

We will keep iterating on it.   Reaction from others has been very positive and we are free to use the photos they provided. -- The shell (including stock photos) for this whole thing was generated by something like ChatGPT!

**Comment by bnmnetp** [comment]
Also, I'll probably feature this in my July newsletter, and we can give people a heads up on the CSAwesome and MobileCSP lists so they will know its all good.
