### ISSUE TITLE
styling issues

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#299]

**Comment by bnmnetp** [comment]
In working through the list of issues in https://github.com/orgs/RunestoneInteractive/projects/8

I've noticed that there are a few issues to work on in the post-harmonious world of React and non-React.

You may recall that one big change we made to the Runestone css was we wrapped runestone rules that we not specific to a particular component so that they are  children of a `.ptx-runestone-container` OR `.runestone-sphinx`

In a non-react build the `.ptx-runestone-container` is missing.  

This causes a few weird things.

1. the pencil popup no longer pops up
2. the bust menu doesn't work when the page is scrolled.
3. Missing colors on the progress bar and buttons


Today I experimented with manually adding the `.ptx-runestone-container` back.

1. the pencil popup works again
2. the bust menu now completely disappears when you scroll and when not scrolled there are alignment problems.
3. colors on the progress bar and buttons are what they should be.

So, I'm proposing that Rob adds the `.ptx-runestone-container` back to the body (peter suggested actually putting it on the html tag.

But then we will some help in getting the menu bar stuff cleaned up.

**Comment by bnmnetp** [comment]
Feel free to experiment with http://dev.runestoneacademy.org/ns/books/published/PTXSB/index.html

**Comment by bnmnetp** [comment]
Without the `.ptx-runestone-container`

![Image](https://github.com/RunestoneInteractive/rs/assets/51115/23decd52-121b-439b-85c5-669158673fc3)

With `.ptx-runestone-container` added


![Image](https://github.com/RunestoneInteractive/rs/assets/51115/9d39a5d5-5c2d-44e4-bd8b-d778ae0aa81d)

**Comment by rbeezer** [comment]
Does the work by @davidfarmer at https://github.com/PreTeXtBook/pretext/pull/2018 resolve this?  If so, please close and adjust projects?  If not, please advise on what else is needed.

https://github.com/PreTeXtBook/pretext/commit/0cf50ee61aecc5b94fff12eec19d602973dcc63c

https://github.com/PreTeXtBook/pretext/commit/1ce3b5c9512bd4d188cd2e9cae17135906484ae5

**Comment by bnmnetp** [comment]
Thanks Rob.  I'll do a test build tomorrow with today's nightly just to be sure.  If all goes as I think it should then I will close this.

**Comment by bnmnetp** [comment]
Looks good. Thanks.
