### ISSUE TITLE
Donation advert appearing on course pages for logged in users

### ISSUE THREAD

**Issue by rita-garcia** [RunestoneInteractive/rs#345]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
[UC_COSC122_class-tog](https://runestone.academy/ns/books/published/UC_COSC122_class-tog/index.html)

**What Page were you on**
Introduction https://runestone.academy/ns/books/published/UC_COSC122_class-tog/class-intro.html

**What is your username**
ritagarcia

**Describe the bug**
I noticed a donation advertisement is on the Introduction page and others for the course. It is my understanding that the advert does not appear on the pages for people logged into Runestone. The appearance of the advert raises concerns for the Ethics (IRB) committee at my institution. I was wondering if this could be addressed. 

**Traceback**
No traceback for this issue.

**Javascript Errors**
No errors for this issue

**Comment by bnmnetp** [comment]
Respectfully, those are not advertisements.  This is no different than what Wikipedia does when it asks people for their support.  We provide Runestone as a free service but we have to have some way to pay our bills.  

Asking students to donate when they haven't even had a chance to get to know the service is not very effective, but asking a few weeks into the term gives them a chance to learn more about what we have to offer.

**Comment by rita-garcia** [comment]
Apologies for my use of advertisement. I did not know what else to call these components appearing in the surveys.

The course is being run as a study and the Ethics Committee raised them as a concern for the study participants. This is not something that is used for an entire semester but for one study that takes about 50-60 minutes to complete.

It was my understanding that they would not be present if a person is logged in. Is that not the case?

**Comment by bnmnetp** [comment]
We may be talking about two different things.

1. There are ads that are shown when someone is not logged in.  These ads are served through the Ethical ad network and we derive some revenue from them.
2. There are requests for a donation that are randomly shown to students even when they are logged in.  

I was not aware that you were part of a research study.  For that purpose I can make sure that neither 1 or 2 are shown.

**Comment by bnmnetp** [comment]
You will need to let me know when the students have registered, so that I can mark them as having donated so they won’t see the request for donation.

**Comment by rita-garcia** [comment]
Ok. Can we use this ticket for this information? Also, since it is the entire cohort, can I provide you the course name to mark all the students in this course? I haven't set up the course yet since there are some customisations.

**Comment by bnmnetp** [comment]
Yes, when you are ready just give me the course name and I will  take care of it.   What is your timeframe?

**Comment by rita-garcia** [comment]
I am hoping to get this done in the next 2-3 weeks

**Comment by rita-garcia** [comment]
Hello,

Thank you for this. I will need to construct two more courses that will be
online within the next 2-4 weeks. Do I still need to contact you for these
courses?

Regards,
Rita

**Comment by bnmnetp** [comment]
Yes, how else would I know that they need special treatment?

**Comment by rita-garcia** [comment]
In your previous message you stated "I coded up a way to mark a course so
that no ads or asks for donations will be shown." This gave future courses
was not going to receive the messages.

Regards,
Rita

**Comment by bnmnetp** [comment]
I made a special way to mark a course as being a "supporter" and rather than turn off any ads or asks for students individually I can now do it for an entire course.  But I need to know the course name.  If an institution voluntarily donates on behalf of the students this happens automatically.  But in your case, since you are part of a study, I will do it manually, but you need to tell me the name of the course.

**Comment by rita-garcia** [comment]
That makes sense. Thank you for the clarification and I will reach out when the other courses are created and populated with student information.

**Comment by bnmnetp** [comment]
They do not even need to be populated with students.  All I need is the name of the courses you want to be exempt.

**Comment by rita-garcia** [comment]
Hello, 

I created the six courses. Below are the names and links to them. 

1. **universityofcanterbury_uc-python-swap_cosc131** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-python-swap_cosc131/index.html
2. **universityofcanterbury_uc-python-swap_COSC121** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-python-swap_COSC121/index.html
3. **universityofcanterbury_uc-python-swap_COSC122** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-python-swap_COSC122/index.html
4. **universityofcanterbury_uc-p3pt_COSC131** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-p3pt_COSC131/index.html
5. **universityofcanterbury_uc-p3pt_COSC121** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-p3pt_COSC121/index.html
6. **universityofcanterbury_uc-class-tog_COSC122** - https://runestone.academy/ns/books/published/universityofcanterbury_uc-class-tog_COSC122/index.html

**Comment by bnmnetp** [comment]
Rita,

I have marked all of your courses in my database so that your students should not be asked for a donation on signup, nor at any point during the use of the study book.

I'm sorry for the confusion, we have 1000's of courses starting at this time of the year and I get all kinds of questions and requests.  I was not aware that you were part of Barb's study.

Brad

**Comment by rita-garcia** [comment]
No problem, I understand. Thank you for doing the edits.

Regards,
Rita
