### ISSUE TITLE
Parsons problems are not displaying correctly in the spaced practice tool

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#350]
**What Course are you in**
py4e-int

**What Page were you on**
spaced practice tool

**What is your username**
barbarer

**Describe the bug**
The Parsons problems are not showing as blocks.
![Screenshot 2023-08-30 at 6 00 24 PM](https://github.com/RunestoneInteractive/rs/assets/43884467/89402a9f-f6e7-4f32-9254-5ce4b3dbe6e6)

**Comment by bnmnetp** [comment]
Should be fixed
