### ISSUE TITLE
c++ unittests with catch.hpp broken

### ISSUE THREAD

**Issue by wrigjl** [RunestoneInteractive/rs#352]
**What Course are you in**
thinkcpp / overview

**What Page were you on**
overview: `cpp_units`

https://runestone.academy/ns/books/published/overview/ActiveCode/clangs.html

Just press "Save & Run".

**What is your username**
wrigjl

**Describe the bug**
C++ unittests are broken. catch.hpp uses MINSIGSTKSZ and expects the definition to be a constexpr. The Linux folks have decided to define MINSIGSTKSZ in terms of sysconf() which... is not a constexpr.

This happens when `_GNU_SOURCE` or `_SC_SIGSTKSZ_SOURCE` are defined (which appears to be default today).

**Traceback**

```
In file included from /usr/include/signal.h:328,
                 from /usr/include/catch.hpp:8007,
                 from test.cpp:8:
/usr/include/catch.hpp:10791:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
10791 |     static constexpr std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/sigstksz.h:24,
                 from /usr/include/signal.h:328,
                 from /usr/include/catch.hpp:8007,
                 from test.cpp:8:
/usr/include/unistd.h:640:17: note: ‘long int sysconf(int)’ declared here
  640 | extern long int sysconf (int __name) __THROW;
      |                 ^~~~~~~
In file included from test.cpp:8:
/usr/include/catch.hpp:10850:45: error: size of array ‘altStackMem’ is not an integral constant-expression
10850 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};
      |                                             ^~~~~~~~~~~~```

**Javascript Errors**

Thankfully, this is not javascript.

**Comment by wrigjl** [comment]
It would appear other projects fix this by upgrading to newer version of Catch2.

Reference: https://github.com/OffchainLabs/arbitrum-classic/pull/1812

**Comment by bnmnetp** [comment]
Thanks,

I have no idea what the solution is.  But if you can give me some steps I will be happy to incorporate them to the current process

Brad
