### ISSUE TITLE
FR: add course id to LTI link for clip board

### ISSUE THREAD

**Issue by wrigjl** [RunestoneInteractive/rs#353]
**Is your feature request related to a problem? Please describe.**

The LTI link presented to me in the LTI integration tab of the instructor page is missing the course ID

**Describe the solution you'd like**

I'd like to get the LTI link copied to my clipboard with the course ID attached.

Instead of:

```
https://runestone.academy/runestone/lti?assignment_id=123456
```

I'd like to get:

```
https://runestone.academy/runestone/lti?assignment_id=123456&custom_course_id=my_course_id
```

**Comment by bnmnetp** [comment]
Hmmm,  doesn't seem hard at all.

Should this be the default?  Should adding the custom_course_id be an option?

**Comment by bnmnetp** [comment]
A question from Discord.... What is the rational for changing the link?  You can configure the custom_course_id for your class in your LMS so that you don't have to have it on every link.

**Comment by wrigjl** [comment]
This is a misunderstand of LTI on my part. The key for me is to use "custom parameters" in Moodle, like so:

```
custom_course_id=mycourseid
```
