### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by valdezge** [RunestoneInteractive/rs#355]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot

**What Page were you on**

**What is your username**

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by valdezge** [comment]
hi i need to reset password

**Comment by bnmnetp** [comment]
There is a password reset available through the website, or your instructor can also reset your password.

**Comment by cccstud** [comment]
I also need a password reset but the won't recognize my username: efowle

**Comment by bnmnetp** [comment]
What do you mean that the site won't recognize your username?  You don't get an email?  That is usually beyond our control, as some schools block external emails.  If it gives you a message on the site that your username does not exist then we don't have that username in our database.

**Comment by cccstud** [comment]
I did receive the email and when I reentered the username to recover the password it states it as invalid.

**Comment by bnmnetp** [comment]
I don't know what is going on... maybe a screenshot might help clarify what you are doing.  The password reset mechanism works fine for 100's of people every day.  So I don't know what would be different for you.

**Comment by cccstud** [comment]
![Runestone](https://github.com/RunestoneInteractive/rs/assets/158081516/68535dfb-c149-476d-be83-44b21c3de64b)
![Runest](https://github.com/RunestoneInteractive/rs/assets/158081516/38791071-f6cd-4e9f-94bc-afe664c2ef10)

**Comment by bnmnetp** [comment]
I just typed your username into my browser and clicked reset password and it said email sent.

**Comment by cccstud** [comment]
I got the email and I was able to do a reset.

Thank you for your help.
