### ISSUE TITLE
Timestamps not consistent from page to page

### ISSUE THREAD

**Issue by Tanaquil18** [RunestoneInteractive/rs#367]
When I'm on the grading page, I see times that are inconsistent.  The due date for the assignment is in local time, but the timestamp on the student submission is in UTC time.  I would like them both to be local time.

<img width="893" alt="timestampoff" src="https://github.com/RunestoneInteractive/rs/assets/7978733/3b67c4a7-6f63-43ff-baf4-339a17aa1f30">

No picture for this, but going to the Instructor's Page and selecting Students Online shows local time, but going to Instructor's Page, then Student Progress and clicking on a student's name shows UTC time, as does the file you get when you download a student's activity.  I would like those to be local time as well, ideally, or at least for there to be a warning that it's UTC time.

**Comment by solijonovam** [comment]
I will be exploring this issue

**Comment by solijonovam** [comment]
issue #393 is dealing with the same issue

**Comment by bnmnetp** [comment]
Yes, I'm going to close this one, since you have claimed the other issue and there is a link between the two.
