### ISSUE TITLE
Test Failures

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#37]
@bjones1  -- The tests are all running locally just fine, but I'm getting a weird version mismatch on urllib3 in the CI.

I can't figure out exactly where this is coming from, but you are a lot more familiar than I am.  Have a look at any of the recent tests and let me know if you have any ideas.

https://github.com/RunestoneInteractive/RunestoneComponents/runs/6678392007?check_suite_focus=true

Thanks

**Comment by bjones1** [comment]
AFAIK, fixed now...
