### ISSUE TITLE
Reading assignment pages with no interactives are always scored as 0%

### ISSUE THREAD

**Issue by ascholerChemeketa** [RunestoneInteractive/rs#378]
If a page is part of a reading assignment, but has no interactive elements, like this
https://author.runestone.academy/ns/books/published/welcomecs2/csp-name-procedures_chapter-summary.html?mode=browsing
Students always get 0% on the autograde

I believe the problem is in `do_autograde` which starts with `score = 0` and then checks for questions. If no questions, it ends up doing:
```
                save_points = 0
                logger.debug("no points for %s on %s", sid, name)
```

Looks like should be some logic to check the row count, and if 0, give them 100%.

**Comment by bnmnetp** [comment]
Hmmm, I'll need to investigate this some more...  nobody has pointed out this kind of behavior in an RST book in a lot of years so it feels like something more is going on.  The way it has always worked is that if there are N activities on the page we count N+1 because we give them 1 interaction just for opening the page.

**Comment by ascholerChemeketa** [comment]
Here is what the autograder shows:
![image](https://github.com/RunestoneInteractive/rs/assets/7787413/7be9abbd-aeaf-46ba-a883-af532f76b4b0)

![image](https://github.com/RunestoneInteractive/rs/assets/7787413/c55977e3-f1a2-4c05-9799-2925cbef17bf)

![image](https://github.com/RunestoneInteractive/rs/assets/7787413/cf8db9a1-ae1a-4826-b98c-7633265f1c7c)

It is clearly not giving credit for pages with no activities.


I was going to do some testing, but I'm still slowly slogging through getting the rsmono repo set up for efficient development.

**Comment by ascholerChemeketa** [comment]
Everyone has 76.92 as there are 10 pages/activities that have completable activities and 3 reading pages without anything on them.

**Comment by bnmnetp** [comment]
I wasn't questioning whether they were getting 0, I was questioning whether this is a simple autograder problem.  It feels more like something is not the same in the database between RST and PreTeXt .

**Comment by ascholerChemeketa** [comment]
Ahhh...

Yes, I don't remember this behavior last year with RST based book and setting up assignments in basically the same way. It does seem probable that this is another Pretext DB issue.

**Comment by bnmnetp** [comment]
Can you send me the course name and assignment.  I'll try to do some sleuthing to see what the deal is.  I have a suspicion that it is something to do with subchapter identifiers and there is a place in the grader where we are not doing the translation properly.

**Comment by bnmnetp** [comment]
Nevermind... I was able to easily recreate the problem locally.  It is what I suspected, and I've got an initial fix.  I'll do some more testing and try to get it live this week.

**Comment by ascholerChemeketa** [comment]
Great! Thanks.

**Comment by bnmnetp** [comment]
@mattboelkins -- Maybe you were running into something similar...
