### ISSUE TITLE
Peer Instruction questions authored in PTX do not load LaTeX macros

### ISSUE THREAD

**Issue by mitchkeller** [RunestoneInteractive/rs#382]
**What Course are you in**
uw-madison_MATH475_fall23

**What Page were you on**
Peer instruction (instructor and student), in the Peer instruction 5.1 assignment

**What is your username**
mitchkeller

**Describe the bug**
The PI questions that are part of this assignment (from Chapter 5) use macros that are defined in docinfo/macros. These macros are not defined when the PI question is loaded as part of the PI interface, causing math to not be rendered.

**Comment by bnmnetp** [comment]
Pretty easy fix for this one.  But I need to have reliable internet to test before I release.

**Comment by bnmnetp** [comment]
This one should be fixed. Light testing, so Let me know and I'll close.

**Comment by mitchkeller** [comment]
The questions that had failed to render math before for me are now rendering correctly, so I think you're good to close this. Thanks!
