### ISSUE TITLE
Please disable donation message for study

### ISSUE THREAD

**Issue by rita-garcia** [RunestoneInteractive/rs#384]
**Please check the current issues** 
Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**

**What is your username** rita-garcia

**Describe the bug**
I am involved in a study with Dr Barb Ericson using Runestone. I have three courses that need the donation message disabled per the university's IRB requirement. This is a similar request made in a [previous ticket](https://github.com/RunestoneInteractive/rs/issues/345
). Can you please disable the donation message for the following courses so that we are complaint with the IRB. Thanks!

- [universityofcanterbury_uc-python-swap_sumsem_23](https://runestone.academy/ns/books/published/universityofcanterbury_uc-python-swap_sumsem_23/index.html)
- [universityofcanterbury_uc-class-tog_sumsem_23
](https://runestone.academy/ns/books/published/universityofcanterbury_uc-class-tog_sumsem_23/index.html)
- [universityofcanterbury_uc-class-tog_sem2_23](https://runestone.academy/ns/books/published/universityofcanterbury_uc-class-tog_sem2_23/index.html)

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here: 

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Done

**Comment by rita-garcia** [comment]
Thanks! Barb created one more course for the study. Do you mind disabling the donation message for this study too. You can find it here:
https://runestone.academy/ns/books/published/uc-class-exp2/index.html

Much appreciated!

**Comment by bnmnetp** [comment]
done

**Comment by rita-garcia** [comment]
Apologies, one more course. I believe this will be the last one we will add to the study. Please disable the donation message for the following study:
https://runestone.academy/ns/books/published/universityofcanterbury_uc-python-swap2_summer23

Thank you advance!
