### ISSUE TITLE
Changing course does not change course

### ISSUE THREAD

**Issue by Alex-Jordan** [RunestoneInteractive/rs#385]
When I am logged in to RA, on a course index page, I try to use the dropdown menu to change course. I click "Change course" and then I am on a page listing all courses I am in. I select the course I would like to move to. But it takes me back to the course index page where I started, for that first course. (I am able to change course in other ways, like using the dropdown menu at the top left.) 

Here is a video of what happens.

https://github.com/RunestoneInteractive/rs/assets/4732672/bb4add62-21a2-4fe5-a1f8-8bde55a61232

**Comment by Alex-Jordan** [comment]
Hmm, well I _thought_ I could use that top left dropdown to change course, but at least right now, I cannot. I get this console error if I make a selection there.

<img width="889" alt="Screenshot 2023-10-08 at 5 02 12 PM" src="https://github.com/RunestoneInteractive/rs/assets/4732672/6a763986-5625-4967-94db-fefe172dd62a">

**Comment by bnmnetp** [comment]
That is so odd... I have never had one other person report that the change course menu under the 👤 menu didn't work....  I change between 25 courses all day.  Moreover the change_course function is defined right in the template for the course page...

More investigation will be required.

**Comment by bnmnetp** [comment]
Trying to figure out why you are missing these other items...  You should for sure see back to textbook...

<img width="541" alt="Screenshot 2023-10-08 at 8 38 36 PM" src="https://github.com/RunestoneInteractive/rs/assets/51115/4cf035a6-2e13-44e5-98c7-8dbf7c809773">

**Comment by Alex-Jordan** [comment]
I don't see them. Just hard refreshed this url: https://runestone.academy/ns/course/index on Chrome, on MacBook, MacOS 13.4. that seems tied to the second issue, which as far as I remember only just started. The first issue is something I have experienced always, and I just worked around it instead of reporting (sorry!) That has been on multiple devices (although probably all MacBookPros).

Is there a drop-in I should try to meet you at this week? As long as this only affects me, it's not urgent...

**Comment by bnmnetp** [comment]
Are you doing this in an instructor account a student account or an account that is a bit of both?

**Comment by Alex-Jordan** [comment]
I have two accounts: jordan and jordanstudent. Both get a little bit of both instructor and student use, but it's supposed to be that jordanstudent is only for me being a student. Current status:

Chrome, logged in as jordanstudent. I'm able to use the menu on the right to Change Course, select a course, and it works. Unlike my video. The "Back to textbook" and other things are missing no matter which course I am in. If I try to use the dropdown on the left to change course, I get that console error.

Firefox, logged in as jordan.  I'm able to use the menu on the right to Change Course, select a course, and it works. Unlike my video. If I'm in my ORCCA course (portlandcommunitycollege_orcca_fall23), the "Back to textbook" and other things are _present_ and the change course dropdown works. If I'm in Chrissy's AC course (franciscan_mth162_F23), those things are missing and the dropdown doesn't work.

It seems like if I am a course instructor, and I am in that course, things work. But if I am a user in a course where my user is not the instructor, things are missing and I get the change_course console error. Also now I cannot replicate the issue from my video. (Any chance you changed something that affected that?)

**Comment by bnmnetp** [comment]
Fixed.  Will be live this weekend.
