### ISSUE TITLE
rs readme image not loading on Github repo

### ISSUE THREAD

**Issue by fairsilas** [RunestoneInteractive/rs#397]
**What Course are you in**
The issue is  the rs readme on GitHub.

**What Page were you on**
Readme.rst (the landing page of the GitHub repo.)

**What is your username**
fairsilas

**Describe the bug**
Image at the end of the readme on GitHub does not load on the GitHub repo, but it loads if accessed through the GitHub Pages site.
![image](https://github.com/RunestoneInteractive/rs/assets/78548914/7544488b-17db-46db-b47b-f4034a63f3ca)

**Comment by bnmnetp** [comment]
This seems to be working now.  The image comes from the badgr site so I think the problem was on their end.
