### ISSUE TITLE
Datafiles counted as required activities in assignments

### ISSUE THREAD

**Issue by ascholerChemeketa** [RunestoneInteractive/rs#412]
Datafiles (in pretext book) do not show as required activities on the page, but default to required activities when the page is used as part of a Reading assignment.

Sample page:
https://runestone.academy/ns/books/published/welcomecs2/csp-repeat-images_a-library-of-image.html

It shows only 2 activities (read page, and run one activecode).

When that page is used in an assignment, it shows 10 activities, 8 required (last row):
![image](https://github.com/RunestoneInteractive/rs/assets/7787413/202ebd0b-0ff5-48a7-a248-3456105814cb)

**Comment by bnmnetp** [comment]
The fix for this needs two parts:

- [ ] Fix the manifest processing to mark datafiles as optional in the questions table.
- [ ] Fix add_or_update_assignment_question to **check** for optional

The second of those appears to be a very old bug...

**Comment by bnmnetp** [comment]
Should all be fixed in the next update

**Comment by bnmnetp** [comment]
Pushed out a release last night.  This should be fixed.

**Comment by bnmnetp** [comment]
Pushed out a release last night.  This should be fixed.
