### ISSUE TITLE
Pre-Build Docker Runtime Requirement in the Documentation

### ISSUE THREAD

**Issue by stevensonmichel** [RunestoneInteractive/rs#413]
**Issue Description**
In the Documentation, there is no explicit mention of letting Docker run in the background prior to building and deploying books. As a consequence, any added book will not be running on the servers, causing the build/deploy commands to crash. This is a necessary step upon developing and adding books to the Runestone Database.

**Comment by stevensonmichel** [comment]
Currently fixing that issue.

**Comment by pearcej** [comment]
I was going to post this as an issue before seeing this. My students are new to Docker (although I gave them readings and walk-throughs), but several students stopped docker rather than just opening a new terminal when they wanted to build and deploy a book.
