### ISSUE TITLE
Documentation should be explict on Python version requirements for dev set-up

### ISSUE THREAD

**Issue by pearcej** [RunestoneInteractive/rs#414]
**Describe the bug**
Some of my students on older machines failed to do all recommended updates in WSL2 Ubuntu. 

They get the following error:
"The currently activated Python version 3.8.10 is not supported by the project (^3.10)"

It would probably be better to include the Python version requirements in the list of prerequisites when Python is first mentioned in the documentation.

**Comment by bnmnetp** [comment]
I agree and I'll add this to the documentation.  Python3.8 is not supported anymore.  It is several years old.  The current release is 3.12 We currently use 3.10 in production but I'll be moving that to 3.11 very soon.
