### ISSUE TITLE
Unit test results don't clear when you get a compile-time error - this confuses students

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#417]
I was in a timed midterm in py4e-int.  A student had an error in her unit test results that claimed the function she was writing wasn't defined.  However, it was clearly there.  On review after the midterm I see that she had commented out her code at one point that defined the function and got the error in the unit test area but then uncommented it later and had a syntax error so the code didn't compile.  We should clear out any old unit tests stuff when they run the code again.

**Comment by bnmnetp** [comment]
Is this using Python in the browser? Or is it using JOBE?  Every run of a python program in the browser has a clean environment each time you run it.

**Comment by barbarer** [comment]
It is Python in the browser during a timed exam.  It was the second to last
problem in the timed exam at
https://runestone.academy/assignment/student/doAssignment?assignment_id=162876
for the ebook Fall23-SI206-TTh.  The student was hanan husein.
[image: image.png]
[image: image.png]

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan

**Comment by bnmnetp** [comment]
So, the issue is that because there was a syntax error, the unit tests never ran and the old unit test results were still displayed.  Which was confusing.

**Comment by barbarer** [comment]
RightSent from my iPhoneOn Nov 3, 2023, at 4:53 PM, Bradley Miller ***@***.***> wrote:﻿
So, the issue is that because there was a syntax error, the unit tests never ran and the old unit test results were still displayed.  Which was confusing.

**Comment by bnmnetp** [comment]
Fixed
