### ISSUE TITLE
Things are not displaying correctly in timed exams - fill in the blank, Parsons, and write code 

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#418]
In a timed exam (using py4e-int) some question types: fill in the blank, Parsons, and write code are not displaying normallly. They usually have a black boarder and background color, but are just transparent.
![Screenshot 2023-11-03 at 1 30 46 PM](https://github.com/RunestoneInteractive/rs/assets/43884467/ddbdba55-fca2-467d-a220-59217dfadfa4)
![Screenshot 2023-11-03 at 1 30 34 PM](https://github.com/RunestoneInteractive/rs/assets/43884467/702d40bd-f589-4a41-b620-14f28a53ac08)
![Screenshot 2023-11-03 at 1 30 27 PM](https://github.com/RunestoneInteractive/rs/assets/43884467/116132b3-a0da-430f-8a3d-0a4b99519365)

**Comment by bnmnetp** [comment]
Fixed
