### ISSUE TITLE
Parsons problems are not displaying correctly in instructor interface after you edit them and generate the HTML

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#419]
If I edit a Parsons problem in the instructors interface and then generate HTML a Parsons problem doesn't display correctly.  If I save it, then it will display correctly later.
![Screenshot 2023-11-03 at 11 18 39 AM](https://github.com/RunestoneInteractive/rs/assets/43884467/106b4178-59ba-463d-a383-90f5f8a057f1)

**Comment by bnmnetp** [comment]
Fixed
