### ISSUE TITLE
CSAwesome java 5.1.7

### ISSUE THREAD

**Issue by 24srsvonkin** [RunestoneInteractive/rs#425]
AP CSAwesome 5.1.7 (java)

The exercise is quite simple however every time I try to compile I get the error "A server error occurred". My code is not the problem as the error shows up even when just running an empty class with no room for errors or running the exercise with no code at all. I am unsure how to resolve this error.

**Comment by bhoffman0** [comment]
This error is given if you do not have a class name. In 5.1.7, you need to put in your class name on line 1 after public class, for example, public class MyClass
