### ISSUE TITLE
Static Dropzones for Matching Questions

### ISSUE THREAD

**Issue by geoff-cox** [RunestoneInteractive/rs#432]
I can think of quite a few applications where a non-randomized dropzone option would improve the look and effectiveness of some matching problems.  See below for two screenshots that illustrate this.  

I have looked at the dragndrop.js code and have prepared a possible PR for this file, but it assumes an optional flag, such as randomizeDropzone (default = true) exists.

Since I am not familiar with the code infrastructure, I wanted to ask if adding such an option would be feasible (locally).

Thanks, Geoff

![RuneStone-Matching-Screen1](https://github.com/RunestoneInteractive/rs/assets/63681414/dd26d299-76e6-4a64-a613-e3d8a2cf2a9b)
![RuneStone-Matching-Screen2](https://github.com/RunestoneInteractive/rs/assets/63681414/f790ae1d-51ca-4ca8-8595-1ba2cffb4480)

**Comment by bnmnetp** [comment]
Great examples, and totally a use case I'm sure others would like.

😳 in glancing at the code, I see that in the constructor we look for `data-random` and set `this.random` accordingly.  But then we never pay any attention and just randomize.

There should be a :randomize: option in the python code in `dragndrop.py` that is processed in the defined run method.  If present it should add the data-random to the `TEMPLATE_START` string on line 45.

**Comment by geoff-cox** [comment]
Thanks for the quick reply. I attempted to model the changes based on mchoice.js and multiplechoice.py, but I am not sure if I got it 100%. Hopefully, I understood your suggestion.

**Comment by bnmnetp** [comment]
Thanks, The PR works as advertised.

@rbeezer -- flagging you on this for later.
