### ISSUE TITLE
Java primitive types: explain origins of names

### ISSUE THREAD

**Issue by DonaldEPayne** [RunestoneInteractive/rs#463]
**Is your feature request related to a problem? Please describe.**
In section "1.3.2. Data Types" at https://runestone.academy/ns/books/published/csawesome/Unit1-Getting-Started/topic-1-3-variables.html , it says:

> There are two types of variables in Java: primitive variables that hold primitive types [...]. The primitive types on the Advanced Placement Computer Science A exam are:

> - int - which store integers (numbers like 3, -76, 20393)
> - double - which store floating point numbers (decimal numbers like 6.3 -0.9, and 60293.93032)
> - boolean - which store Boolean values (either true or false).

1. These names might seem obscure to a new programmer.
2. In the list of doubles, a comma is missing between the first example (6.3) and the second (-0.9).

**Describe the solution you'd like**
I'd like to add more to the descriptions:
"Primitive" types are directly supported by the "machine code" of the CPU (Central Processing Unit). All CPUs have "primitive" (one-step) instructions to operate on these types (e.g., add, multiply or compare); while the object types are manipulated by a series of lines of code. Older programming languages such as FORTRAN directly support only primitive types.
- "double" is short for "double-precision floating-point number". Floating-point means a decimal number where the decimal point can "float" or move to store very large or very small numbers (e.g., 5.972&nbsp;x&nbsp;10<sup>24</sup>, the mass of the Earth in kg, or 3&nbsp;×&nbsp;10<sup>−26</sup>&nbsp;kg, the mass of one molecule of H<sub>2</sub>O, water). It's called "double" because it occupies twice as much storage space as the "float" type (**single**-precision floating point), which can store about 7 significant decimal digits, vs. about 15 for a "double".
- "boolean" is named after the logician [George Boole](https://en.wikipedia.org/wiki/George_Boole), the inventor of Boolean algebra.

**Describe alternatives you've considered**

**Additional context**

**Comment by bhoffman0** [comment]
Thanks, I added some of the background details about the names of these types. I did not add text about CPU machine code because I feel it is outside the scope of this course and would require more complex discussions about hardware.
