### ISSUE TITLE
Student unable to enroll in a new course

### ISSUE THREAD

**Issue by jonnycomes** [RunestoneInteractive/rs#469]
Course name: MAT-252-24Spring
Username: ChillChen

**Issue:**
One of my students is unable to enroll in my course MAT-252-24Spring. The student has used Runestone before with the username ChillChen. The course that he completed in the past is CSC-150-TH-23Spring. 

When ChillChen tries to enroll in MAT-252-24Spring he gets a pop-up error message. I checked all the fields he was entering multiple times, and am convinced the error is not in what he is entering.

There was a similar issue last fall with user lyndadanielson. I believe the issue was the existence of multiple accounts with the same username or email address. If I remember correctly, deleting the extra user fixed the issue.

**Comment by jonnycomes** [comment]
Thanks for the quick response. Sorry for not including the error message before. Here it is:

"Value already in database or empty"

**Comment by bnmnetp** [comment]
So, yes, there are two different usernames for this student with the same email address.  One of them must have been added via a CSV file.

This can be fixed, self service, by changing the email address for either of the usernames.  I really don't like to delete student accounts.  The student can also delete their own account.  The email address is not an identifier for the student.  Only the username. emails are only used for password resets.

**Comment by jonnycomes** [comment]
Thanks Brad!
