### ISSUE TITLE
All Progress Deleted

### ISSUE THREAD

**Issue by trangela** [RunestoneInteractive/rs#477]
I am a student taking cmsc-210-spring-2024, an introductory Python course. My username is TRANAN7@VCU.EDU.

I opened up an assignment I finished only to see all of my progress has been erased. I have been working chapters ahead, and I realized ALL of my work was gone. Every single chapter was "not started," all of the activities were undone, and all of the questions were unanswered. I went from having 100% in every chapter to 0%. I am on Chrome.

**Comment by bnmnetp** [comment]
I'm not sure what you mean by progress being "erased."  Having just checked,  I can assure you that there are thousands of database entries recording your work.

**Comment by trangela** [comment]
> I'm not sure what you mean by progress being "erased." Having just checked, I can assure you that there are thousands of database entries recording your work.

I am unsure of how to access that. I have tried attaching a screenshot that may explain better than I can with words. When I look at the chapters in my notebook I have definitely previously completed, It now shows no work having been completed.

<img width="1364" alt="Screen Shot 2024-04-04 at 12 44 16 PM" src="https://github.com/RunestoneInteractive/rs/assets/112021133/2a2ba702-258a-4d13-8a81-6b32bcc7c5d5">

**Comment by bnmnetp** [comment]
All that tells me is that your instructor has not graded that reading assignment yet.  Which, since it is not due until april 5th does not seem unreasonable.

As the developer and maintainer I can access the database directly, and I can tell you that you have answered all of these question in Chapter 10.

```
+----------------+
| div_id         |
|----------------|
| question10_1_1 |
| question10_1_2 |
| question10_2_1 |
| question10_3_1 |
| question10_3_2 |
| question10_3_3 |
| question10_4_1 |
| question10_5_1 |
+----------------+
```

So the data is recorded so that when your instructor grades the assignment you will get credit.

**Comment by trangela** [comment]
> All that tells me is that your instructor has not graded that reading assignment yet. Which, since it is not due until april 5th does not seem unreasonable.
> 
> As the developer and maintainer I can access the database directly, and I can tell you that you have answered all of these question in Chapter 10.
> 
> ```
> +----------------+
> | div_id         |
> |----------------|
> | question10_1_1 |
> | question10_1_2 |
> | question10_2_1 |
> | question10_3_1 |
> | question10_3_2 |
> | question10_3_3 |
> | question10_4_1 |
> | question10_5_1 |
> +----------------+
> ```
> 
> So the data is recorded so that when your instructor grades the assignment you will get credit.

Sorry, I chose a bad example. It looks that way for all of my past assignments as well. Additionally, I want to be able to see what I have answered in order for studying purposes. Here are some examples from a past chapter:
<img width="1364" alt="Screen Shot 2024-04-04 at 2 29 50 PM" src="https://github.com/RunestoneInteractive/rs/assets/112021133/b9e7239e-3392-4faa-8e65-cada6c53415e">
<img width="1364" alt="Screen Shot 2024-04-04 at 2 30 04 PM" src="https://github.com/RunestoneInteractive/rs/assets/112021133/1770d4bc-aa67-41fd-8a6b-f563f30a0b2b">

**Comment by trangela** [comment]
> Your answers to both of those questions **are** in the database. We really do not ever ever delete things.
> 
> But, it is a mystery why your answers are not restored. In my test books, the answers to questions including fill in the blanks are restored for me. I've not had reports from anyone else about answers not restoring. So maybe you can help. If you can recall anything odd that happened? Have you modified your profile? Did something happen with your class registration? Did you install some new extension or plugin to Chrome?
> 
> Sometimes in these cases bringing up the Javascript console will reveal a clue.

I do remember something odd, although I was not paying my full attention. When I logged in, I saw a donation screen and I pressed a button that said something along the lines of "maybe another time." After pressing it, all of my progress became invisible. It was different than the little donation boxes within the chapters. Also, I recently downloaded a video player extension to chrome that allows me to play videos faster/slower.

**Comment by bnmnetp** [comment]
That is odd... You should only see the donation screen when you first register for the course.

Whether you donate or not has no impact on how we treat you as a student.  Other than removing the little asks from the pages if you do.

Have you tried logging in with a different browser, or using incognito mode to see if that changes things?  The video extension doesn't sound like a culprit, but you never know.   If you disable it and things go back to normal that would tell us a lot. The Javascript console would probably show something there. opt-cmd-i on a mac to bring that up.

**Comment by trangela** [comment]
> That is odd... You should only see the donation screen when you first register for the course.
> 
> Whether you donate or not has no impact on how we treat you as a student. Other than removing the little asks from the pages if you do.
> 
> Have you tried logging in with a different browser, or using incognito mode to see if that changes things? The video extension doesn't sound like a culprit, but you never know. If you disable it and things go back to normal that would tell us a lot. The Javascript console would probably show something there. opt-cmd-i on a mac to bring that up.

Thank you for the advice! It worked.
