### ISSUE TITLE
Dead Link on 9.13.4 of the AP CSA Java Course

### ISSUE THREAD

**Issue by Maimas2** [RunestoneInteractive/rs#479]
This issue occurs on page 9.13.4 of the AP CSA Java Course.

The page provides a link to extra practice, which points to [here](http://practiceit.cs.washington.edu/list.jsp), but this link is dead on the washington.edu server and gives a 404 error.

I'm assuming that there should be a new link or it should be removed.

**Comment by bhoffman0** [comment]
Thanks I've changed the link to https://practiceit.cs.washington.edu/problem/list (open Java book and click on Ch. 9). It will be live probably this weekend.
