### ISSUE TITLE
Updated Link to firewalled replit

### ISSUE THREAD

**Issue by MIfoodie** [RunestoneInteractive/rs#486]
**What Course are you in**
CSAwesome

**What Page were you on**
https://runestone.academy/ns/books/published/csawesome/Unit1-Getting-Started/javaIDEs.html

**What is your username**
AReinowski

**Describe the bug**
Replit is now using a different link for firewalled Replit as documented at https://docs.replit.com/additional-resources/firewalled-replit. The new link is https://firewalledreplit.com/. The old link shown on the CSAwesome book at the link above is https://firewealled.replit.com/.

**Comment by bhoffman0** [comment]
Thanks. Fixed link and replit description. Will be live this weekend.
