### ISSUE TITLE
Students can copy and paste on timed exam - please turn this off

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#488]
During a timed exam students can copy text from a question and paste the question into Gen AI and then copy the solution from Gen AI to the exam question. Please disable copy and paste during a timed exam.

**Comment by bnmnetp** [comment]
Done closed by [a7eddfb](https://github.com/RunestoneInteractive/rs/commit/a7eddfb355f96f3bb8e2977af4116361395ce478)
