### ISSUE TITLE
Typo - essentially a bug if you run the code.

### ISSUE THREAD

**Issue by domxavier** [RunestoneInteractive/rs#491]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
pythonds3
Textbook - Problem Solving with Algorithms and Data Structures 3rd edition

**What Page were you on**
6.11.3. Heap Operations

**What is your username**
parlegee

**Describe the bug**
It is a type. An undefined variable is used in Listing 6. Even the variable name is `i`, the variable name `cuir_idx` is used, which is not defined.

**Traceback**
```
def heapify(self, not_a_heap):
    self._heap = not_a_heap[:]
    i = len(self._heap) // 2 - 1
    while i >= 0:
        self._perc_down(cuir_idx)
        i = i - 1
```

**Comment by bnmnetp** [comment]
Thanks.  Fixed.
