### ISSUE TITLE
Adding an author to Runestone

### ISSUE THREAD

**Issue by geoff-cox** [RunestoneInteractive/rs#495]
I would like to know if my project could be added to Runestone. It is currently in development, but I was curious about how it will look and function on your server.

https://github.com/geoff-cox/debookrs

Thanks,
Geoff

**Comment by bnmnetp** [comment]
Hi Geoff,

Things look the same, but behave differently... answers are saved to the database and restored etc...

I can get you set up as an author.  But you need to let me know your username on Runestone Academy.  Then you can use the author interface to pull and build your book and preview it there.

I took a look at your book, but there is a mistake in the `publication/runestone.ptx`

You have a tag `<html platform="runestone">` That is not correct.  See https://github.com/bnmnetp/Runestone2PreTeXt

If you can remember how that tag got there in the first place I would love to know so we can correct the documentation or the code that generated that file.

**Comment by geoff-cox** [comment]
Thanks! My Runestone username is gcox. I will fix the publication file before deploying the book.
