### ISSUE TITLE
Answer Not Saved

### ISSUE THREAD

**Issue by HongzhengL** [RunestoneInteractive/rs#498]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**

- OCC-CSC240-DataStructures

**What Page were you on**

- Chapter 8.10

**What is your username**

- hli3801

**Describe the bug**

When I was trying to save my answer by clicking `Check me` bottom, an error message pop up, as shown in the following.

**Traceback**

```
Error: Your action was not saved!
                    The error was Error: Failed to save the log entry
                    Status: 500
                    Status Code: 500
                    Detail: "none".
                    Please report this error!
```

EDIT: I switched multiply browsers and got the same result.

**Comment by bnmnetp** [comment]
Thanks for the report.  We found the bug.  I've made a temporary workaround so you should not see that message.  the real fix will go live this week sometime.
