### ISSUE TITLE
Failed to save answer and error on any button clicked on assignment page

### ISSUE THREAD

**Issue by ashok052** [RunestoneInteractive/rs#505]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Knowing the course will help us a lot
https://www.coursera.org/learn/python-basics/home/welcome

**What Page were you on**
https://py3.umsi.education/assignment/student/doAssignment?assignment_id=2

**What is your username**
ashokkumarvadde@gmail.com

**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

When I click "Save & Run" button for any of the questions in the assignment, the table below the question for "expected" and "actual" values shows the values are matching and green color. But there are a couple of java script pop-ups as shown in the images below. 
<img width="451" alt="Screenshot 2024-07-15 at 2 42 57 PM" src="https://github.com/user-attachments/assets/4cf846e8-6f1d-4b6a-9d63-1aa6979d2ec8">

<img width="439" alt="Screenshot 2024-07-15 at 2 41 27 PM" src="https://github.com/user-attachments/assets/c292a61b-4160-4284-8bfa-b2cc1b0aee6d">

At the bottom of the page, when I click on "Compute Score for Assignment" , I get the below pop-up. This also happens on clicking any button on the above assignment page.
<img width="455" alt="Screenshot 2024-07-15 at 2 45 20 PM" src="https://github.com/user-attachments/assets/3baedabe-1432-4223-a99a-9f1831cae70a">

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

<img width="542" alt="Screenshot 2024-07-15 at 2 51 09 PM" src="https://github.com/user-attachments/assets/3a5cf0dd-143c-4ca3-a4e5-2f3a9176bdf6">

**Comment by bnmnetp** [comment]
Hi @ashok052,

Thanks for the report.   We really can't do anything to help you with the coursera courses as we have no control over those servers or what build of our software they are running.

I do recognize this as an old problem that we fixed some time ago.

Brad

**Comment by ashok052** [comment]
Thanks. I will report it on the coursera site
