### ISSUE TITLE
I am unable to see my first assignments on my course

### ISSUE THREAD

**Issue by vunag** [RunestoneInteractive/rs#507]
My course: 
My user is 
Name Guy Schreiber

**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
odedhighschool_studentcsp_fall24

**What Page were you on**
When clicking manage assignments I can see two assignments I created.
Going back to the course and clicking the assignments link I get no assignment list

**What is your username**
Gaiush

**Describe the bug**
Can't try my assignments and see how they work as they do not appear in the assignment link

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by vunag** [comment]
It seems they were not visible to students and that was the issue. I still don't understand the interface for peer instruction.
In the course settings there is group size for peer instruction which is not clear what it is and does not appear on the manual

**Comment by bnmnetp** [comment]
The group size is a default setting for how many people you have in a group for peer instruction.
I can't answer a question like "I don't understand..."  If you have specific questions I encourage you to ask them in our discord where I'm sure people will be happy to explain it to you.  I *think* we may also have a video of one of our workshops where we go into detail about how to do peer instruction.
