### ISSUE TITLE
error message on assign page

### ISSUE THREAD

**Issue by tarumoy43** [RunestoneInteractive/rs#512]
**Please check the current issues**  when i was trying to submit all the answers of the assignment the page is not responding it was showing unable to process.

**What Course are you in**
https://coursera.org/share/a29c7b4e14f2396eb72338edc0405d7b

**What Page were you on**
https://py3.umsi.education/assignment/student/doAssignment?assignment_id=2

**What is your username**
tarumoy gayen
**Describe the bug**
![Screenshot 2024-07-24 112915](https://github.com/user-attachments/assets/20cdd7f9-e6ea-4c7a-96e1-53371218f8ca)
![Screenshot 2024-07-24 112831](https://github.com/user-attachments/assets/71940b2e-6d0e-43d4-ae9a-fc99b6ca3b6d)

**Traceback**

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Please contact the support people at coursera.  We have no control over those servers.

**Comment by bnmnetp** [comment]
They are aware of the problem and are working on it.  Since the problem has been fixed in this repository for months, I'm closing this issue.
