### ISSUE TITLE
problem editing all questions (cl-reference-5-12, cl-reference-5-13 ,cl-reference-5-14 )from course cppds-mich lecture 5

### ISSUE THREAD

**Issue by ishikag2004** [RunestoneInteractive/rs#517]
Course -cppds-mich

assignment builder -> search question -> edit interface

ishikag

I was trying to edit all questions from lecture 5 (map lecture). questions name: cl-reference-5-12, cl-reference-5-13, cl-reference-5-14. All other lectures have been updated. I wasn’t able to edit them as it's not letting me edit it using main edit button or make new questions for it. It redirects me to a blank screen in former scenario and  the changes do not get saved in the latter. Only the code for the question needs to be copied and pasted from the lecture again due to some changes in the slides. in addition the edit button in/below preview question also does not work for any question.

Uncaught SyntaxError: Identifier 'Configuration' has already been declared (at mathjaxknowl3.js:1:1)
index-BWYFnudW.js:40 TypeError: Cannot read properties of undefined (reading 'map')
    at Ome (index-BWYFnudW.js:2205:12144)
    at rN (index-BWYFnudW.js:38:19554)
    at EK (index-BWYFnudW.js:40:44104)
    at bK (index-BWYFnudW.js:40:39822)
    at lie (index-BWYFnudW.js:40:39748)
    at CE (index-BWYFnudW.js:40:39598)
    at x_ (index-BWYFnudW.js:40:35960)
    at tF (index-BWYFnudW.js:40:36765)
    at Ef (index-BWYFnudW.js:38:3288)
    at index-BWYFnudW.js:40:34286
h_ @ index-BWYFnudW.js:40Understand this error
index-BWYFnudW.js:38 Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at Ome (index-BWYFnudW.js:2205:12144)
    at rN (index-BWYFnudW.js:38:19554)
    at EK (index-BWYFnudW.js:40:44104)
    at bK (index-BWYFnudW.js:40:39822)
    at lie (index-BWYFnudW.js:40:39748)
    at CE (index-BWYFnudW.js:40:39598)
    at x_ (index-BWYFnudW.js:40:35960)
    at tF (index-BWYFnudW.js:40:36765)
    at Ef (index-BWYFnudW.js:38:3288)
    at index-BWYFnudW.js:40:34286

<script>
--
  | $(document).on("runestone:pre-login-complete", function() {
  | console.log("pre-login-complete");
  | })
  | var runestoneMathReady = new Promise((resolve) => window.rsMathReady = resolve);
  | window.MathJax = {
  | tex: {
  | inlineMath: [['\\(','\\)']],
  | tags: "none",
  | tagSide: "right",
  | tagIndent: ".8em",
  | packages: {'[+]': ['base', 'extpfeil', 'ams', 'amscd', 'newcommand', 'knowl']}
  | },
  | options: {
  | ignoreHtmlClass: "tex2jax_ignore\|ignore-math",
  | processHtmlClass: "process-math",
  | renderActions: {
  | findScript: [10, function (doc) {
  | document.querySelectorAll('script[type^="math/tex"]').forEach(function(node) {
  | var display = !!node.type.match(/; *mode=display/);
  | var math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
  | var text = document.createTextNode('');
  | node.parentNode.replaceChild(text, node);
  | math.start = {node: text, delim: '', n: 0};
  | math.end = {node: text, delim: '', n: 0};
  | doc.math.push(math);
  | });
  | }, '']
  | },
  | },
  | chtml: {
  | scale: 0.88,
  | mtextInheritFont: true
  | },
  | loader: {
  | load: ['input/asciimath', '[tex]/extpfeil', '[tex]/amscd', '[tex]/newcommand', '[pretext]/mathjaxknowl3.js'],
  | paths: {pretext: "https://pretextbook.org/js/lib"},
  | },
  | startup: {
  | pageReady() {
  | return MathJax.startup.defaultPageReady().then(function () {
  | console.log("in ready function");
  | rsMathReady();
  | }
  | )}
  | },
  | };
  | </script>
  |  
  | <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  | <script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>
  | <script src="https://pretextbook.org/js/lib/knowl.js"></script>
  | <script src="https://pretextbook.org/js/lib/mathjaxknowl3.js"></script>
  |  
  |  
  | <script type="module" crossorigin src='/assignment/react/assets/index-BWYFnudW.js'></script>
  |  
  |  
  | <link rel="stylesheet" crossorigin type="text/css" href="/assignment/react/assets/index-Bz00Bcvm.css" />
  |  
  |  
  |  
  | </head>
  |  
  | <body>
  | 
  |  
  |  
  | <script type="text/javascript">
  | if(typeof eBookConfig === "undefined") {
  | eBookConfig = {};
  | }
  | eBookConfig.host = '';
  | eBookConfig.app = eBookConfig.host+'/runestone';
  | eBookConfig.ajaxURL = eBookConfig.app+'/ajax/';
  | eBookConfig.course = "cppds-mich";
  | eBookConfig.logLevel = 10;
  | eBookConfig.loginRequired = true;
  | eBookConfig.python3 = true;
  |  
  | eBookConfig.username = "ishikag"
  | eBookConfig.email = "ishikag@umich.edu"
  |  
  | eBookConfig.isInstructor = true;
  |  
  | eBookConfig.isLoggedIn = true;
  |  
  | eBookConfig.useRunestoneServices = true;
  | eBookConfig.basecourse = "cppds";
  | eBookConfig.gradeRecordingUrl = `${eBookConfig.app}/assignments/record_grade`;
  | eBookConfig.new_server_prefix = "/ns";
  | eBookConfig.websocketUrl = ""
  | eBookConfig.enableDebug = true ? "" == "True" : false;
  | </script>
  | <div class="hidden-content" style="display: none">
  | \(  \)
  | </div>
  | <div id="root"></div>
  |  
  |  
  | 
  |  
  |  
  | </body>
  | </html>

<script>
$(document).on("runestone:pre-login-complete", function() {
    console.log("pre-login-complete");
})
var runestoneMathReady = new Promise((resolve) => window.rsMathReady = resolve);
window.MathJax = {
  tex: {
    inlineMath: [['\\(','\\)']],
    tags: "none",
    tagSide: "right",
    tagIndent: ".8em",
    packages: {'[+]': ['base', 'extpfeil', 'ams', 'amscd', 'newcommand', 'knowl']}
  },
  options: {
    ignoreHtmlClass: "tex2jax_ignore|ignore-math",
    processHtmlClass: "process-math",
    renderActions: {
        findScript: [10, function (doc) {
            document.querySelectorAll('script[type^="math/tex"]').forEach(function(node) {
                var display = !!node.type.match(/; *mode=display/);
                var math = new doc.options.MathItem(node.textContent, doc.inputJax[0], display);
                var text = document.createTextNode('');
                node.parentNode.replaceChild(text, node);
                math.start = {node: text, delim: '', n: 0};
                math.end = {node: text, delim: '', n: 0};
                doc.math.push(math);
            });
        }, '']
    },
  },
  chtml: {
    scale: 0.88,
    mtextInheritFont: true
  },
  loader: {
    load: ['input/asciimath', '[tex]/extpfeil', '[tex]/amscd', '[tex]/newcommand', '[pretext]/mathjaxknowl3.js'],
    paths: {pretext: "https://pretextbook.org/js/lib"},
  },
  startup: {
    pageReady() {
      return MathJax.startup.defaultPageReady().then(function () {
      console.log("in ready function");
      rsMathReady();
      }
    )}
},
};
</script>

<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
<script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>
<script src="https://pretextbook.org/js/lib/knowl.js"></script>
<script src="https://pretextbook.org/js/lib/mathjaxknowl3.js"></script>

    <script type="module" crossorigin src='[/assignment/react/assets/index-BWYFnudW.js](https://runestone.academy/assignment/react/assets/index-BWYFnudW.js)'></script>

    <link rel="stylesheet" crossorigin type="text/css" href="[/assignment/react/assets/index-Bz00Bcvm.css](https://runestone.academy/assignment/react/assets/index-Bz00Bcvm.css)" />

    </head>

    <body>
      
      

<script type="text/javascript">
  if(typeof eBookConfig === "undefined") {
      eBookConfig = {};
  }
  eBookConfig.host = '';
  eBookConfig.app = eBookConfig.host+'/runestone';
  eBookConfig.ajaxURL = eBookConfig.app+'/ajax/';
  eBookConfig.course = "cppds-mich";
  eBookConfig.logLevel = 10;
  eBookConfig.loginRequired = true;
  eBookConfig.python3 = true;
  
  eBookConfig.username = "ishikag"
  eBookConfig.email = "ishikag@umich.edu"
    
        eBookConfig.isInstructor = true;
    
  eBookConfig.isLoggedIn = true;
  
  eBookConfig.useRunestoneServices = true;
  eBookConfig.basecourse = "cppds";
  eBookConfig.gradeRecordingUrl = `${eBookConfig.app}/assignments/record_grade`;
  eBookConfig.new_server_prefix = "/ns";
  eBookConfig.websocketUrl = ""
  eBookConfig.enableDebug = true ? "" == "True" : false;
</script>
  <div class="hidden-content" style="display: none">
    \(  \)
  </div>
<div id="root"></div>

      
      
      
    </body>
</html>

**Comment by bnmnetp** [comment]
These questions are saved badly in the database, the json does not have the right information for the editor to restore the questions.  

I can delete them from the database so that you can re-enter them.  But let me know when, in case you want to get a screen capture of the previews.
