### ISSUE TITLE
Instructor guide 404ing

### ISSUE THREAD

**Issue by mcnuttandrew** [RunestoneInteractive/rs#518]
The [instructor guide](https://runestone.academy/runestone/static/instructorguide/index.html) linked from several places 404s. Should this be the issue covered on the [FAQ](https://blog.runestone.academy/pages/faq.html#why-can-t-i-access-the-instructor-page), the linked page there too throws an error (cf https://runestone.academy/ns/books/published/instructorguide/frontmatter-1.html?mode=browsing)

**Comment by bnmnetp** [comment]
The official home should be https://guide.runestone.academy

I thought I had updated most places to use that link, but there are many.  So... if you could be specific about which links are broken that would be helpful.  Or feel free to make a PR that fixes it for me. 😄

**Comment by bnmnetp** [comment]
I think I found them all.
