### ISSUE TITLE
Can't Access the Assessment in Python Basics COURSERA

### ISSUE THREAD

**Issue by VarunVainala** [RunestoneInteractive/rs#519]
**What Course are you in**
Python Basics Coursera

**What Page were you on**
on Assessment - Programming in Python page, I'll provide link below
https://py3.umsi.education/assignment/student/doAssignment?assignment_id=2

**What is your username**
VAINALA VARUN TEJA
b21ee020@kitsw.ac.in
(in Coursera)

**Describe the bug**

When I type the code in the first problem in my assignment, it doesn't  let me type instead it shows red mark on the code and error pops up instantly telling it is unprocessable with error code 422. I searched online for a solution but couldn't find anywhere. And with lost hope, I thought you would only be the solution for my problem.
![Assesment Error Coursera_1](https://github.com/user-attachments/assets/a76731e0-305a-40ad-b68b-925a8de74093)
![Assesment Error Coursera_1](https://github.com/user-attachments/assets/e6185661-9c68-402a-b104-8680bd6e1e68)
![Assesment Error Coursera](https://github.com/user-attachments/assets/f95210f2-2075-41fa-8596-a5840561a551)

If I run the code same error pops up, If I compute the assignment same error pops up.

I've added Photos of the error for your reference.

**Traceback**
No Traceback.

**Javascript Errors**
Can't find.

**Comment by gyan11799** [comment]
I am also facing same error

**Comment by bnmnetp** [comment]
We have no control over the Coursera servers that run the Runestone software.  You will need to work with Coursera support to resolve your issues.

**Comment by bnmnetp** [comment]
The folks running your course are aware of this issue and how to fix it.  The problem was fixed for Runestone Academy months ago.  So, I'm closing this issue.
