### ISSUE TITLE
Marking exercises as private or  not

### ISSUE THREAD

**Issue by maellis1** [RunestoneInteractive/rs#526]
This seems related to issue #415 

We are developing questions in VT_CS2_Peer_F24

On the Assignments tab of the Instructor's page.  We are editing exercises using the rst approach.

Margaret Ellis is reporting this.  This is part of the Testing the Effects of Peer Discussion grant.

**Describe the bug**
We are trying to set some of the vtcs2 questions to private and some to not be private.   The UI doesn't seem to accurately portray whether they are private or not.  When editing the exercises using the tree of exercises down in the Problems sections, it appears that checking or unchecking the Private checkbox then applies to all the exercises in the book (not sure what gets saved in DB).  I made a video where I change this and save and go look at another exercise and saved it here: https://drive.google.com/file/d/1db8VEa8hEYXjWtueiOYCSVuQI6ur4-qh/view?usp=drive_link

This fix will allow us to share our exercises that have been deemed useful for others.

**Comment by bnmnetp** [comment]
With today's deployment this should be fixed.  In addition, the tree view will include a lock icon for questions that are private in the database.

**Comment by maellis1** [comment]
Thanks! We will  follow up if we have any issues or questions.
