### ISSUE TITLE
LTI hiccup with new canvas course

### ISSUE THREAD

**Issue by maellis1** [RunestoneInteractive/rs#528]
**What Course are you in**
vtcs2_peerplus_fall24_prod
**What Page were you on**
connecting from canvas to assignment "Testing Runestone with Bob 2"

**What is your username**
MargaretEllisHoward

**Describe the bug**
We were setting up the fall canvas course to connect to a Runestone book.  We tried connecting to the existing one and had errors so we started fresh with  vtcs2_peerplus_fall24_prod.  It seems like is should be connecting but it does not and 
This shows up in the window of: https://runestone.academy/runestone/lti?assignment_id=186656
Not logged in due to the following error(s)
First Name is required for this tool to function
<Storage {'assignment_id': ['186656', '186656'], 'ext_ims_lis_basic_outcome_url': 'https://canvas.vt.edu/api/lti/v1/tools/13389/ext_grade_passback', 'tool_consumer_info_version': 'cloud', 'oauth_signature_method': 'HMAC-SHA1', 'oauth_nonce': 'iXv6M3Iu1JLIhA6JE6zBQVxd81gZfj06jMV16KLeE', 'ext_lti_assignment_id': 'f9f5d657-a873-4337-b5c0-51bda9b53f3e', 'launch_presentation_document_target': 'iframe', 'context_label': 'CS_2114_Fall2024', 'context_id': '7b1b11ed2ea98596bed1b1a89879c164f1fbf399', 'custom_course_id': 'vtcs2_peerplus_fall24_prod', 'tool_consumer_instance_contact_email': 'notifications@instructure.com', 'oauth_signature': 'tyViB1oi61NFObSD5vu3c8EtyzI=', 'roles': 'Instructor', 'ext_roles': 'urn:lti:instrole:ims/lis/Instructor,urn:lti:instrole:ims/lis/Student,urn:lti:role:ims/lis/Instructor,urn:lti:role:ims/lis/Learner/NonCreditLearner,urn:lti:role:ims/lis/Mentor,urn:lti:sysrole:ims/lis/User', 'ext_outcome_submission_submitted_at_accepted': 'true', 'oauth_version': '1.0', 'tool_consumer_info_product_family_code': 'canvas', 'custom_canvas_enrollment_state': 'active', 'launch_presentation_return_url': 'https://canvas.vt.edu/courses/196002/assignments', 'ext_outcome_submission_needs_additional_review_accepted': 'true', 'custom_canvas_assignment_title': 'Testing Runestone with Bob 2', 'resource_link_title': 'Testing Runestone with Bob 2', 'custom_canvas_assignment_points_possible': '10', 'lti_version': 'LTI-1p0', 'launch_presentation_locale': 'en', 'oauth_consumer_key': 'vtcs2_peerplus_fall24_prod-d92e291c-58c8-11ef-b443-0242ac130008', 'ext_outcome_submission_prioritize_non_tool_grade_accepted': 'true', 'ext_outcomes_tool_placement_url': 'https://canvas.vt.edu/api/lti/v1/turnitin/outcomes_placement/13389', 'tool_consumer_instance_guid': 'yDz0MxxBs02YM08vCb8fQ85ISbDXw62vLT6KiA6s:canvas-lms', 'ext_outcome_data_values_accepted': 'url,text', 'context_title': 'Softw Des & Data Structures', 'lis_outcome_service_url': 'https://canvas.vt.edu/api/lti/v1/tools/13389/grade_passback', 'oauth_callback': 'about:blank', 'user_id': 'c8a37ad7c2deebe82bc05d95bed2d3f72d626aad', 'resource_link_id': '5fbad47d4866d5a643a7833cdebb0d14a90838c0', 'ext_outcome_result_total_score_accepted': 'true', 'lti_message_type': 'basic-lti-launch-request', 'oauth_timestamp': '1723480990', 'tool_consumer_instance_name': 'Virginia Tech'}>

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

Javascript console says: jquery.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)

**Comment by bnmnetp** [comment]
Just as the error message tells you, the user has to have a first name.

**Comment by maellis1** [comment]
I am able to do this okay from the other canvas course to Runestone, so I'm not sure why I don't have a first name here but I do in the other canvas course.  How can we look into this? My profile in canvas has a first middle and last name.

**Comment by bnmnetp** [comment]
I really don't know... You might ask about this on the discord in the `lti_community_support` channel.  I've never used canvas, and I don't have a canvas test environment.  But I can see the line of code that checks to see if we are getting a first name from canvas and if we don't that is the error you see.  Its probably just a misconfiguration of canvas on your side that is causing the problem.
