### ISSUE TITLE
Progress Erased

### ISSUE THREAD

**Issue by NateDeLo** [RunestoneInteractive/rs#529]
All of my progress has been erased. I was on the last assignment of module 3 and now it's showing that I haven't completed any of the previous assignments. Coursera is showing that I have watched all of the videos, but everything on the runestone side is messed up.

**What Course are you in**
Python Basics Course 1

**What Page were you on**
Module 3

Nate_Delo@outlook.com

![Screenshot 2024-08-22 110840](https://github.com/user-attachments/assets/399eb773-c11a-4702-be40-8674f6107044)
![Screenshot 2024-08-22 110655](https://github.com/user-attachments/assets/d295e421-8bcc-4209-a011-8430555b9758)
![Screenshot 2024-08-22 110935](https://github.com/user-attachments/assets/1eda7650-9fc7-4bea-bb15-7afc5396e5d1)

**Comment by NateDeLo** [comment]
When I go through the interactive text book on Runestone none of the my progress is there. It's all gone.

**Comment by bnmnetp** [comment]
Those are not our servers, they are run by the university of michigan.  We run the servers on Runestone.Academy
