### ISSUE TITLE
Add Project to Runestone Academy

### ISSUE THREAD

**Issue by braughtg** [RunestoneInteractive/rs#530]
We have been working on a set of activities (The GitKit) for introducing the git and Github forking workflow to students. We would like to have this project added to Runestone Interactive.

The URL of the project is: https://github.com/HFOSSedu/GitKit-Text

Note: The text is not completely finished but we would like to gain access to the "draft" available via the "author interface" as described in https://pretextbook.org/doc/guide/html/sec-publishing-to-runestone-academy.html.

Please advise if anything further is needed.

**Comment by bnmnetp** [comment]
Great!

The book is online here:  https://runestone.academy/ns/books/published/gitkit/frontmatter.html?mode=browsing

I had to change the clone location to gitkit to match the document-id, but that is a one time thing.

You will need runestone usernames for me to add you as authors so let me know, and then those who are authors will. be able to use the author interface to pull and rebuild and deploy the book on demand.

**Comment by braughtg** [comment]
Super!  Thanks @bnmnetp.

The following users should have author access for now.
- braught
- kwurst
- rlampy
- lpostner
