### ISSUE TITLE
Link to book in assignments page changed to another textbook

### ISSUE THREAD

**Issue by mrasamny** [RunestoneInteractive/rs#543]
**What Course are you in**
202501-CSCI-120-02

**What Page were you on**
Assignments

**What is your username**
mrasamny

**Describe the bug**
I assigned four reading assignments, each linked to a section in my course book.  Today, I created a reading assignment, and when I tried selecting the section from my course book, it seemed to have defaulted to a C++ book.  The current course book is correct; however, the reading assignment page seems to be connected to a C++ book.  It seems that even my old assignments only show the C++ book.  I attached an image of the assignments page with the C++ chapters appearing when I expand the reading link at the bottom. 

<img width="588" alt="assignment_page" src="https://github.com/user-attachments/assets/a3237aec-e256-4ecb-af10-b6ec324ee7bf">

**Comment by bnmnetp** [comment]
Sorry, there was a problem with an update yesterday.  Fixed now.

**Comment by mrasamny** [comment]
Thank you.

--
Regards,
Marwan Rasamny, Ph.D.
Chairperson & Associate Professor
Division of Physics, Engineering, Mathematics, and
Computer Science
Delaware State University
Mishoe Science Center 330
1200 North Dupont Highway
Delaware State University
Dover, Delaware 19901


Dept Phone: +1.302.857.6640
Direct:     +1.302.857.7896
Fax:        +1.302.857.6552
URL:        PEMaCS<https://cast.desu.edu/departments/division-physics-engineering-mathematics-computer-science>
[cid:96f44f72-4741-44ec-8fd0-ee83c72c5a34]
________________________________
From: Bradley Miller ***@***.***>
Sent: Monday, September 30, 2024 9:01 AM
To: RunestoneInteractive/rs ***@***.***>
Cc: Marwan Rasamny ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] - Re: [RunestoneInteractive/rs] Link to book in assignments page changed to another textbook (Issue #543)


Sorry, there was a problem with an update yesterday. Fixed now.
