### ISSUE TITLE
Access blocked for users from China

### ISSUE THREAD

**Issue by soqank** [RunestoneInteractive/rs#550]
**Please check the current issues** 
I searched through the issues for the following keywords: access, login, china, cloudflare, blocked

**What Course are you in**
CSAwesome

**What Page were you on**
Login, Assignments, Instructors Page, any page

**What is your username**
Teacher_Ben, and all of my students

**Describe the bug**
The site has been blocked by cloudflare for Chinese users. I tried accessing the site through the school network, my home network, cellular network. The only thing that gets through is some VPN locations.

**Traceback**
N/A
**Javascript Errors**
N/A

![Image 10-10-24 at 2 34 PM](https://github.com/user-attachments/assets/7b3b4f28-670e-4ddc-9a5d-d56e08094cd4)

**Comment by tc-kirby** [comment]
I'm getting the same problem here in the UK. 19 of my pupils logged on at the same time this morning (09:20 BST) and a significant number of them got a message similar to this.

I get:
Cloudflare Ray ID: 8d0540605d76d1f9 • Your IP: 194.72.114.126 • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing)

**Comment by bnmnetp** [comment]
I apologize for the inconvenience.  Runestone has been repeatedly attacked by a denial of service attack for the last month.  I finally moved runestone.academy onto the cloudflare network.  Unfortunately many of the attack bots originate from China.

It may take some time to get the system tuned to keep the bad guys out and allow the good guys in.

**Comment by bnmnetp** [comment]
Legitimate users from around the world should be fine now.

**Comment by soqank** [comment]
Awesome!!! And I’ve noticed it’s running even faster now. Thank you for
your hard work.
