### ISSUE TITLE
Display 0 scores from chapter activities on Spreadsheets

### ISSUE THREAD

**Issue by JeffreyMFried** [RunestoneInteractive/rs#552]
I teach multiple chapters from the text for a given module in our course.  The easiest way to grade chapter activities is to download the .csv file from the spreadsheet showing the students' scores.  But registered students only show up if they've completed at least one activity in one of the sections in a chapter.  This means I must align the spreadsheets for multiple chapters to get a score for the week's readings.  This process is tedious and prone to errors.  There's no reason why no activities completed for a given section can't be displayed as a 0.

**Comment by bnmnetp** [comment]
So, I think that you are asking about the "Number of Activities Correct" report under the Chapter Activity page?  Is that correct?

**Comment by bnmnetp** [comment]
PS - I added this feature very quickly because of a request from someone who is a longtime supporter and contributor.  If it is so easy then please go ahead and make a PR.  Otherwise please don't be condescending.

**Comment by bnmnetp** [comment]
Deon

**Comment by JeffreyMFried** [comment]
Yes, it’s the page that shows the completed activities of each student

**Comment by JeffreyMFried** [comment]
I thought you were contacting me about bug 572 which I just wrote yesterday which, at least to me, is a much higher priority than 552.  They are about the same section of your app.  The problem outlined in 572 is because I can’t download or even see the spreadsheet.  552 arose because without the 0 scores shown in the spreadsheet, I have to align the spreadsheets from multiple chapters to get a single grade, adding blank columns and shifting other columns to account for the students with zero activities completed.  #552 adds extra hassle and error possibilities, but at least I can get the spreadsheet.  #572 prevents me from being able to assess the spreadsheet and I have to examine the individual completion pages for each student and tally the scores manually.

**Comment by bnmnetp** [comment]
I don't think you mean #572, and I don't see another issue created by you.
