### ISSUE TITLE
Documentation for build script out of date

### ISSUE THREAD

**Issue by ascholerChemeketa** [RunestoneInteractive/rs#568]
Read the docs for the build script are out of date with changes in this commit:
https://github.com/RunestoneInteractive/rs/commit/7702766d9ead9840a516d67bf15c3b20212b0c81

You can no longer issue `build` from the `rs` directory.

Instructions should either point at the new directory or explain how to run (with args) via poetry.

**Comment by bnmnetp** [comment]
I thought that I **had** updated the docs to state that you needed to do `poetry shell` and then you can run build from *anywhere* in the `rs/**` hierarchy.   It is no longer `build.py`

**Comment by ascholerChemeketa** [comment]
You can't pass the poetry `build` script parameters in the same way that the documentation shows. That would be good to update.
