### ISSUE TITLE
Open Discrete section 3.7 #4 and 6

### ISSUE THREAD

**Issue by dianenead** [RunestoneInteractive/rs#570]
**Please check the current issues** Many bug reports are duplicates, this just creates more work for us. Searching the issues first may give you your answer or a workaround! If not adding new information to an existing report is much more helpful than a new report.

**What Course are you in**
Discrete_LewisFA24_Nead

**What Page were you on**
section 3.7, problems #4 and 6
**What is your username**
mend
**Describe the bug**
A clear and concise description of what what you were trying to accomplish and what went wrong. Vague statements like X does not work are not helpful. Imagine if one of your students sent you an email that said, "My program doesn't work, whats wrong with it?" Could you help them with only that to go on?

Both these problems don't seem to correct correctly.  
![Screen Shot 2024-11-06 at 8 50 07 PM](https://github.com/user-attachments/assets/ae525043-2ca3-438f-9b72-e2cd8ad5612b)
![Screen Shot 2024-11-06 at 8 50 56 PM](https://github.com/user-attachments/assets/2877bf27-f93b-4dcf-8941-4a4c819697eb)

Thank you for your responses to all my comments as I work through this course the first time!

**Comment by dianenead** [comment]
If you put in the correct answer in the first question, it marks it as incorrect, but then blank is marked correct.

BTW: Is there anyway students can game this and find the answers?  I had a student that was not working much, then all of the sudden he is getting 100%, even on this problem that is not correct.  It seems he realizes that you can put blanks in these and get full credit.  I don't know how he gets the 100% when others don't (except 2 others who do the same thing).  

I did not do the rest of the parts of these problems, it is late so not sure if they work either.

**Comment by bnmnetp** [comment]
@oscarlevin -- this one's for your

**Comment by bnmnetp** [comment]
@dianenead we have tested lots of scenarios so I do not think that there is an easy way to spoof the system to get full credit.

**Comment by oscarlevin** [comment]
Thanks for the report.  There were some errors in the source that were messing up these particular problems.  Those should be fixed and the updates should be live.
