### ISSUE TITLE
Save Edits button on Assingment Editing window doesn't response

### ISSUE THREAD

**Issue by dipayan1109033** [RunestoneInteractive/rs#573]
**What Course are you in**
Course ID: UHCS1336-Fall24-JS

**What Page were you on**
https://runestone.academy/runestone/admin/assignments > Editing an assignment 

**What is your username**
dipayanbiswas

**Describe the bug**
I am trying to edit an assignment for an active code template. It was working fine last week, but now I can't "Save Edits." I can generate/view HTML of my edit, but when I click on "Save Edits," no save successful message pops up. I tried creating a new assignment, with some random text it was successful but when I added more text for the question description, it doesn't save, same issue.

**Comment by bnmnetp** [comment]
duplicate of #572

**Comment by dipayan1109033** [comment]
My issue solved. Thank you.
