### ISSUE TITLE
Grade Book Seems to populate incorrect values

### ISSUE THREAD

**Issue by monsterworks-ludi** [RunestoneInteractive/rs#574]
**What Course are you in**
montgomery_cwu_172

**What Page were you on**
https://runestone.academy/runestone/dashboard/grades

**What is your username**
montgoaa

**Describe the bug**
Gradebook (online and downloaded versions) appears to be populated with incorrect/nonsensical values. This is a new issue which arose between November 10 and November 8. I have uploaded the gradebook download from November 8 (11-08.csv) and the gradebook download from November 10 (11-10.csv). Columns for "FName" and "LName" seem to have been filled with "Not Started". The column for "E-mail" is filled with values from the "UName" column, and scores seem to have been jumbled (but I'm not quite sure what the pattern is; maybe all the "Not Started" values have floated to the left?).

Edit: With multiple people seeing this, I feel comfortable removing the links to the csv files (since I just realized one contains some emails of my students). Just making it (slightly) tougher for a robot to sweep them up.

**Comment by bnmnetp** [comment]
Ugh! Sorry, I thought I was making a tiny little change, and it looked right in my quick testing, but NO I can see it is wrong.  I'll get a fix i

In the meantime, does the alpha gradebook look right for you?

**Comment by monsterworks-ludi** [comment]
Yeah, its those little changes which will kill you. The alpha gradebook looks correct and I can access the grades I need using it until it gets fixed.

Aaron

**Comment by gramlogic** [comment]
I'm seeing something very similar for course csci150-24fa-michael, at the same url. The "Not Started" values are also in the first assignment, even though the students all completed it. In my case, it looks like all the scores for all assignments are still there, but they have all been shifted one column to the right.

**Comment by bnmnetp** [comment]
I have a fix in place.  Will push it live after the school day ends in the USA.

Brad

**Comment by bnmnetp** [comment]
Both look good to me now.  Please let me know so I can close.

**Comment by monsterworks-ludi** [comment]
Looks good to me.
