### ISSUE TITLE
Open Discrete 4th edition 4.2 #5

### ISSUE THREAD

**Issue by dianenead** [RunestoneInteractive/rs#578]
One of my students and I think 4.2 #5 on open discrete is not working correctly:

![Screen Shot 2024-11-16 at 4 49 52 PM](https://github.com/user-attachments/assets/c4c58647-ccea-4832-a36f-832fe24d2d80)

**Comment by bnmnetp** [comment]
@oscarlevin -- tagging you

**Comment by oscarlevin** [comment]
Yup, found a typo in the code that generated that problem.  Rebuilding now and it should be fixed online soon.

BTW, feel free to report these on the book's github issues and I might see them sooner: https://github.com/oscarlevin/discrete-book/issues

**Comment by bnmnetp** [comment]
@oscarlevin I wonder if I should add a link to the course home page, similar to the link for books that have a google group or other social site for discussion...  The link to report bugs could be customized on the library page, with the rs issues page as the fallback...

**Comment by oscarlevin** [comment]
That would be a reasonable addition I think.
