### ISSUE TITLE
Students are reporting issues when running activecode in Chapter 10: Files and Chapter 14: More About Iteration

### ISSUE THREAD

**Issue by ladanielson** [RunestoneInteractive/rs#585]
**What Course are you in**
CSC-150-24Fall

**What Page were you on**
This is occurring on various pages for some, but not all, students.  I'll give two specific examples.
1) Assignment Ch 10 Problems: Activity: 10.15.4 ActiveCode (ac9_10_1)
and
2) Chapter 14.2 The while Statement: Activity: 14.2.7 ActiveCode (ac14_2_2).

**What is your username**
1) jacob-graviet
2) sabuhi-abbasov
lyndadanielson

**Describe the bug**
1) Jacob's correct code gives the error SyntaxError: bad input on line 6 (which appears to be the autograder code).  When I run Jacob's code for grading, I see no errors and he passes the unit tests.
2) Sabu's correct code gives SyntaxError: bad input on line 7.  When I run Sabu's code for grading, I see no errors and he passes the unit tests.

There are more students encountering these errors and unable to run code in Chapter 10 and 14. There are also students with no errors.  We have not had any such issues prior to this in the term.  Thank you, Lynda

**Traceback**
If you got here through the Bug Report page and there was a stack trace, please paste it here

**Javascript Errors**
Many many errors can be quickly diagnosed from the Javascript Console error log. On Chrome this is View --> Developer --> Javascript Console, on Safari ⌥⌘i or Develop --> Show Web Inspector on Firefox Tools --> Web Developer --> Toggle Tools

**Comment by bnmnetp** [comment]
Thanks for the report.  We were adding a new feature this past weekend, and it ended up introducing a small backward incompatibility with the book's source code.  Literally the difference between `=====` and `====` that is causing the problem.  I fixed it and updated the book a few minutes ago.

**Comment by ladanielson** [comment]
Thank you for the speedy response!  The issue is resolved.
