### ISSUE TITLE
setSpeed () method missing from downloaded Turtle files

### ISSUE THREAD

**Issue by sarahkmccoy** [RunestoneInteractive/rs#595]
I downloaded the files to run Turtle objects in pickcode.io from 4.4.2.  I cannot find a setSpeed() method for the drawing anywhere.  If I comment out that line, it runs, but the picture just shows completed, rather than being drawn.

I checked the documentation for Simple turtle and Turtle,  and also browsed through all the class files I downloaded, and don't see setSpeed anywhere.

Can you add it to the downloadable files?  Thanks!

**Comment by bnmnetp** [comment]
Sorry, but I have no idea what you are asking for.  I don't know anything about pickcode.io (other than it looks to be a service you have to pay for) or what book 4.4.2 might refer to.  All the drawings by turtles in our books are animated and you would have to use either the tracer or the speed methods to change that.  Python turtle graphics does not have a setSpeed method.

**Comment by bhoffman0** [comment]
I think this is referring to CSAwesome. @mrmazzone added the setSpeed function. You can find his jar files here: https://github.com/MrMazzone/Java-Swing-Turtle-Jar or packaged as a jar: https://github.com/MrMazzone/Turtle-Java-Example

**Comment by sarahkmccoy** [comment]
Hi!  Sorry for not clarifying...I had assumed that the forum was about CS
Awesome.  I checked Mr. Mazzone's files and didn't see it there either...I
would assume it was in the Simple Turtle class?

Thanks!

**Comment by bhoffman0** [comment]
Thanks Joe!

**Comment by sarahkmccoy** [comment]
Thank you!  I see the updated files on Github.  Much appreciated!  I am a
novice programmer and hardly know more than my students...can someone
explain how to handle a jar file?

Also, this process gives a nice example for understanding how class
attributes and methods interact.

This is my just my second time teaching CSA, and CS Awesome has been such a
comforting resource!

Thanks again,
Sarah

**Comment by bnmnetp** [comment]
Sarah,

It sounds like you should sign up for the CSAwesome Google group.  There are lots of helpful people on that list that I'm sure will answer your question about using jar files.

See:  https://groups.google.com/g/teaching-csawesome

**Comment by sarahkmccoy** [comment]
Thanks, I'll do that.  Happy Holidays!
